version: '2'
services:
  #client:
   # build: ./Client
    #ports:
     #- "8080:8080"
    #volumes:
#     - ./Mobile/:/app/Client/
     #- ./WebApp/FrontEnd:/app/Client/
  api:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./WebApp/BackEnd/Api/:/app/Api/
